Авдеев Д.О. №2
IvlevAlexander0/3824B1FI2-1 pull request #35
Opened 2024-10-17 22:10 UTC by qwertewer

2024-10-22 18:38 UTC, IvlevAlexander0 requested changes
Необходимы исправления:
1. В первом режиме аккуратней с rand(), у вас может получиться 0.
2. Во втором режиме проверьте ваш подход к вычислению предполагаемого числа, так как в вашей реализации нельзя получить многие числа, например 502, числа больше 747 или меньше 253.

Также рекомендую использовать бесконечный цикл с break вместо цикла с флагом.

2024-10-26 01:23 UTC, qwertewer commented on AvdeevD/Lab2/Lab2.cpp
> +				num = (rand() + 1) % 1000;
нужно изменить на num = rand() % 1000 + (rand()/1000)

2024-10-28 10:24 UTC, IvlevAlexander0 requested changes
Необходимы изменения:
1. В первом режиме вы всё ещё некорректно генерируете случайное целое число от 1 до 1000.
2. Также некорректная работа с enum (True != true, flag не используется)
3. Во втором режиме добавьте выход, если vrem1 == vrem2.

Также все изменения необходимо вносить в код, а не указывать в обсуждениях.

2024-10-31 21:27 UTC, IvlevAlexander0 requested changes
Необходимы изменения:
1. В си нет типа bool и true соответственно.
2. Всё ещё не правильно генерируете случайные числа. Посмотрите свои записи, я показывал это на одной из пар.

Жду от вас корректные исправления по 02.11 и третью лабораторную по 05.11. Иначе буду вынужден пригласить вас на зачет.    
Также рекомендую тщательней тестировать ваши работы до отправки на проверку.

2024-11-02 14:08 UTC, IvlevAlexander0 approved these changes
Зачтено, но лучше было бы заменить while(true) на while(1).

2024-11-02 14:08 UTC, merged