Погудин Р. А. №4, 5, 6
IvlevAlexander0/3824B1FI2-1 pull request #57
Opened 2024-12-17 03:27 UTC by Chais666

2024-12-17 10:55 UTC, IvlevAlexander0 requested changes
Необходимо удалить файлы от 5 и 6 лабораторной в данном pull request. Это можно сделать так:
1. Перенесите папки Lab4-6 вне вашего локального репозитория.
2. Подтвердите изменения чередой команд: **git add .** ; **git commit -m "del"**; **git push**.
3. Затем внесите обратно ваши папки с лабораторными.
4. Подтвердите отправьте изменения связанные с 4 лабораторной чередой команд: **git add PogudinR/Lab4** ; **git commit -m "lab4"**; **git push**.
5. После у вас в pull request останется только 4 лабораторная (и нужно переименовать pull request).
6. Далее после проверки я внесу ваши изменения в общий репозиторий и вы создадите отдельный pull request для 5 и 6 лабораторной аналогичным образом (**git add PogudinR/Lab№** ; **git commit -m "lab№"**; **git push**, где № - номер лабораторной, которую вы хотите сдать или изменить).

Ниже результаты проверки.

2024-12-17 11:09 UTC, IvlevAlexander0 commented
Lab5
Необходимы изменения:
1. При повторной сортировке вы подаёте на вход уже отсортированные данные.

2024-12-17 11:20 UTC, IvlevAlexander0 commented
Lab6
Зачтено, но в arccos должно быть sum = pi/2 - x;. Также несколько рекомендаций: в math.h есть M_PI и в циклах обычно не принято использовать переменную n.

2024-12-18 14:07 UTC, IvlevAlexander0 requested changes
Я писал выше мои замечания при проверки ваших лабораторных. Продублирую замечания для 4. Внести исправления можно командами **git add PogudinR/Lab№** ; **git commit -m "lab№"**; **git push**, где № - номер лабораторной, которую вы хотите сдать или изменить.

Необходимы изменения:
1. Немного не поняли задание. Товары должны храниться в памяти и мы можем, либо посмотреть их описание, либо добавить в чек. Изначально в программе должны быть описаны 5 товаров и мы можем добавить новые, так чтобы штрих-коды не совпадали. («Сканирование» товара - это ввод штрих-кода, который однозначно соответствует товару)
2. Возможно падение программы при вызове 2 и 3 пункта меню до вызова 1.

2024-12-18 14:43 UTC, Chais666 commented
как только эта работа попадет в общий пулл реквест, смогу следующую лабораторную прислать и потом также 6?

2024-12-18 14:49 UTC, IvlevAlexander0 approved these changes
Зачтено. Так как 6 лабораторную я вам зачел, то можете создать совместный pull request для 5 и 6 лабораторных. Только не забудьте поправить 5.

2024-12-18 14:49 UTC, merged